### ISSUE TITLE
Research Daily Quote API

### ISSUE THREAD

**Issue by wwstrothe** [bobpruz/project1#2]

**Comment by bobpruz** [comment]
details of use:

* fetch statement
fetch("https://type.fit/api/quotes")
.then(function(response) {
  return response.json();
})
.then(function(data) {
  console.log(data);
});

*Array returned 
return will be => all in array 1643

* we will need to build random number generator 
length of array => randomize 1 quote 

* how we will display JSON items
display author = data[random number].author 

display quote = data[random number].text
